### ISSUE TITLE
Repost: Crash during instal HyperV4 (swww)

### ISSUE THREAD

**Issue by PedroCordeiroF** [SolDoesTech/HyprV4#90] opened 2024-03-23 14:51 UTC
Repost because i accidentally closed the other issue i opened (sorry)

I'm installing the hyperV4and getting an error on swww installing. ![image](https://github.com/SolDoesTech/HyprV4/assets/156690484/5954d316-8c63-41f0-965c-891c49d99157)
![image](https://github.com/SolDoesTech/HyprV4/assets/156690484/93f7329a-eb47-45df-bbd5-9f8ef1daf3b1)

Note: Some warnings are in Portuguese (because that's my main language)
Note2: I'm a complete beginner, so if i'm doing something wrong point it out :)

**Comment by Speeif** [comment] 2024-03-24 13:47
This issue is a duplicate of https://github.com/SolDoesTech/HyprV4/issues/88.

The AUR repository (where the swww package is downloaded from) has just been updated with a fix. This however presents another issue - which I'll explain the solution for in https://github.com/SolDoesTech/HyprV4/issues/88

edit: I might have jumped the gun. It started working for me out of no where. Maybe you have to run `swww init` and `swww-daemon &` in your terminal, and it works on start-up...? Anyway, try and run the setup script and see if that helps.

**Comment by PedroCordeiroF** [comment] 2024-03-24 22:40
It worked!!! Thanks for the tip.
I appreciate the help.

**Closed as completed** 2024-03-24 22:40 UTC
